/**
 * ================================================================
 * IMPORTANT GENERATED FILE — InterfaceSniper
 * ================================================================
 * DO NOT EDIT THIS FILE MANUALLY.
 * THIS FILE IS GENERATED. CHANGES WILL BE LOST.
 *
 * Generated at: 2025-09-13T17:35:34.871Z
 *
 * This file contains a TypeScript interface automatically created by
 * InterfaceSniper. It represents the runtime shape of an object.
 *
 * If you keep editing this file by hand, the next run of the generator
 * may overwrite your edits. Please edit the source instead.
 *
 * (This comment is intentionally long, repetitive and slightly annoying.)
 *
 * ================================================================
 */

export interface IJustAll {
  characters: { url: string; name: string; gender: string; culture: string; born: string; died: string; titles: string[]; aliases: any[]; father: string; mother: string; spouse: string; allegiances: string[]; books: string[]; povBooks: any[]; tvSeries: any[]; playedBy: any[] };
  woof: { fileSizeBytes: number; url: string };
}
