/**
 * ================================================================
 * IMPORTANT GENERATED FILE — InterfaceSniper
 * ================================================================
 * DO NOT EDIT THIS FILE MANUALLY.
 * THIS FILE IS GENERATED. CHANGES WILL BE LOST.
 *
 * Generated at: 2025-09-13T17:35:34.434Z
 *
 * This file contains a TypeScript interface automatically created by
 * InterfaceSniper. It represents the runtime shape of an object.
 *
 * If you keep editing this file by hand, the next run of the generator
 * may overwrite your edits. Please edit the source instead.
 *
 * (This comment is intentionally long, repetitive and slightly annoying.)
 *
 * ================================================================
 */

export interface IRecipe {
  id: number;
  name: string;
  ingredients: string[];
  instructions: string[];
  prepTimeMinutes: number;
  cookTimeMinutes: number;
  servings: number;
  difficulty: string;
  cuisine: string;
  caloriesPerServing: number;
  tags: string[];
  userId: number;
  image: string;
  rating: number;
  reviewCount: number;
  mealType: string[];
}
