/**
 * ================================================================
 * IMPORTANT GENERATED FILE — InterfaceSniper
 * ================================================================
 * DO NOT EDIT THIS FILE MANUALLY.
 * THIS FILE IS GENERATED. CHANGES WILL BE LOST.
 *
 * Generated at: 2025-10-24T17:12:02.057Z
 *
 * This file contains a TypeScript interface automatically created by
 * InterfaceSniper. It represents the runtime shape of an object.
 *
 * If you keep editing this file by hand, the next run of the generator
 * may overwrite your edits. Please edit the source instead.
 *
 * (This comment is intentionally long, repetitive and slightly annoying.)
 *
 * ================================================================
 */

export interface IyoutubeSearchResults {
  kind: string;
  etag: string;
  nextPageToken: string;
  regionCode: string;
  pageInfo: { totalResults: number; resultsPerPage: number };
  items: { kind: string; etag: string; id: { kind: string; videoId: string }; snippet: { publishedAt: string; channelId: string; title: string; description: string; thumbnails: { default: { url: string; width: number; height: number }; medium: { url: string; width: number; height: number }; high: { url: string; width: number; height: number } }; channelTitle: string; liveBroadcastContent: string; publishTime: string } }[];
}
